import ESMotionCore
import ESMotionDocument
import Foundation

@main
enum ESMotionCommand {
    static func main() throws {
        var arguments = Array(CommandLine.arguments.dropFirst())
        guard let command = arguments.first else {
            printHelp()
            return
        }
        arguments.removeFirst()

        switch command {
        case "help", "--help", "-h":
            printHelp()
        case "validate":
            try validate(arguments)
        case "init":
            try initialize(arguments)
        case "generate-swift":
            try generateSwift(arguments)
        case "pack":
            try pack(arguments)
        case "verify":
            try verify(arguments)
        default:
            throw CommandError.unknownCommand(command)
        }
    }

    private static func validate(_ arguments: [String]) throws {
        guard let path = arguments.first else {
            throw CommandError.missingArgument("manifest path")
        }
        let url = URL(filePath: path).standardizedFileURL
        let document = try MotionDocumentCodec.load(from: url)
        let issues = MotionDocumentValidator.validate(
            document,
            rootURL: url.deletingLastPathComponent()
        )

        if issues.isEmpty {
            print("Valid: \(url.path)")
            return
        }

        for issue in issues {
            print(
                "\(issue.severity.rawValue.uppercased()) "
                    + "\(issue.path): \(issue.message)"
            )
        }

        if issues.contains(where: { $0.severity == .error }) {
            throw CommandError.validationFailed
        }
    }

    private static func initialize(_ arguments: [String]) throws {
        guard let path = arguments.first else {
            throw CommandError.missingArgument("output directory")
        }
        let rootURL = URL(filePath: path, directoryHint: .isDirectory)
            .standardizedFileURL
        let layout = MotionPackageLayout(rootURL: rootURL)
        try layout.prepareDirectories()

        let fallbackSequence = MotionSequence(
            name: "Reduced Motion",
            duration: 0.18
        )
        let document = MotionDocument(
            name: rootURL.deletingPathExtension().lastPathComponent,
            states: [
                MotionState(
                    id: "default",
                    name: "Default",
                    sequenceIDs: [fallbackSequence.id]
                ),
            ],
            sequences: [fallbackSequence],
            reducedMotion: MotionAccessibilityFallback(
                staticStateID: "default",
                sequenceID: fallbackSequence.id
            )
        )
        try MotionDocumentCodec.save(document, to: layout.manifestURL)
        print("Created \(layout.manifestURL.path)")
    }

    private static func generateSwift(_ arguments: [String]) throws {
        guard arguments.count >= 2 else {
            throw CommandError.missingArgument(
                "manifest path and output Swift path"
            )
        }
        let manifestURL = URL(filePath: arguments[0]).standardizedFileURL
        let outputURL = URL(filePath: arguments[1]).standardizedFileURL
        let document = try MotionDocumentCodec.load(from: manifestURL)

        var lines = [
            "// Generated by esmotionc. Do not edit.",
            "import ESMotion",
            "",
            "public enum ESMotionAssets {",
        ]
        for asset in document.assets.sorted(by: { $0.id < $1.id }) {
            let identifier = swiftIdentifier(asset.id)
            lines.append(
                "    public static let \(identifier) = "
                    + "MotionAssetID(\"\(escaped(asset.id))\")"
            )
        }
        lines.append("}")
        lines.append("")
        let source = lines.joined(separator: "\n")
        try source.write(to: outputURL, atomically: true, encoding: .utf8)
        print("Generated \(outputURL.path)")
    }

    private static func pack(_ arguments: [String]) throws {
        guard arguments.count >= 2 else {
            throw CommandError.missingArgument(
                "project directory and output .esmotion path"
            )
        }
        let directoryURL = URL(
            filePath: arguments[0],
            directoryHint: .isDirectory
        ).standardizedFileURL
        let archiveURL = URL(filePath: arguments[1]).standardizedFileURL
        try MotionPackageArchive.pack(
            directory: directoryURL,
            to: archiveURL
        )
        print("Packed \(archiveURL.path)")
    }

    private static func verify(_ arguments: [String]) throws {
        guard let path = arguments.first else {
            throw CommandError.missingArgument(".esmotion archive path")
        }
        let archiveURL = URL(filePath: path).standardizedFileURL
        let temporaryURL = FileManager.default.temporaryDirectory
            .appending(
                path: "ESMotionVerify-\(UUID().uuidString)",
                directoryHint: .isDirectory
            )
        defer {
            try? FileManager.default.removeItem(at: temporaryURL)
        }
        try MotionPackageArchive.unpack(
            archiveURL,
            to: temporaryURL
        )
        let layout = MotionPackageLayout(rootURL: temporaryURL)
        let document = try MotionDocumentCodec.load(
            from: layout.manifestURL
        )
        let issues = MotionDocumentValidator.validate(
            document,
            rootURL: temporaryURL
        )
        guard !issues.contains(where: { $0.severity == .error }) else {
            throw CommandError.validationFailed
        }
        print("Verified \(archiveURL.path)")
    }

    private static func swiftIdentifier(_ value: String) -> String {
        let scalars = value.unicodeScalars
        let mapped = scalars.map { scalar -> Character in
            CharacterSet.alphanumerics.contains(scalar)
                ? Character(String(scalar))
                : "_"
        }
        var result = String(mapped)
        if result.first?.isNumber == true {
            result = "_\(result)"
        }
        return result.isEmpty ? "asset" : result
    }

    private static func escaped(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }

    private static func printHelp() {
        print(
            """
            ESMotion command line tools

              esmotionc validate <manifest.json>
              esmotionc init <project-directory>
              esmotionc generate-swift <manifest.json> <output.swift>
              esmotionc pack <project-directory> <output.esmotion>
              esmotionc verify <archive.esmotion>
            """
        )
    }
}

private enum CommandError: LocalizedError {
    case missingArgument(String)
    case unknownCommand(String)
    case validationFailed

    var errorDescription: String? {
        switch self {
        case .missingArgument(let argument):
            "Missing \(argument). Run 'esmotionc help' for usage."
        case .unknownCommand(let command):
            "Unknown command '\(command)'. Run 'esmotionc help' for usage."
        case .validationFailed:
            "Document validation failed."
        }
    }
}
